### ISSUE TITLE
Hakluyt: strange attributes on names

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/canonical-engLit#13]
e.g., 

```xml
<name reg="  +Russia [47,60] (nation), Asia " type="place" key="tgn,7002435">Russia</name>
```
There are several problems:

1. There is no @reg attribute in the TEI schema;
2. The values for the @keys appear to be references to the Getty Thesaurus of Geographic Names, formatted in an odd way.
3. At least some of this machine-generated markup is wrong

Can someone explain where this came from?

**Comment by lcerrato** [comment]
@cwulfman  No, I have no information. Most of those named entities would have been added by one of the programmers or by Greg.

**Comment by AlisonBabeu** [comment]
HI @cwulfman I think Greg has the most information here because I believe this information was added automatically during the named entity experiments of the early 2000s.

**Comment by cwulfman** [comment]
I'm going to leave them out, then.  There are better ways to do this.

**Comment by lcerrato** [comment]
There are working place names in the current collections such as
`<placeName key="tgn,6001700" >Delium</placeName>`
