### ISSUE TITLE
cannot link to Scaife build -- private repo

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-engLit#8]
I don't believe I can use this in a build until it is no longer private. Just tried a test run.

**Comment by lcerrato** [comment]
made public

**Comment by cwulfman** [comment]
Great; thanks! Do you think it's ok simply to leave the copyright texts, in the Renaissance folder, where they are?

**Comment by lcerrato** [comment]
Are there copyrighted texts or just texts someone thought were copyrighted? If the former, I would move them, yes.

**Comment by AlisonBabeu** [comment]
hi @lcerrato I have no idea,I've never worked through the texts in this collection.

**Comment by lcerrato** [comment]
@AlisonBabeu  All large reference works were restricted as a policy matter. Other works are restricted solely because the header does not indicate any publication information.

I believe, if there was missing info, it was automatically restricted in the absence of affirmative info.
Again, this is part of the whole problem with an orphaned collection.

If you would prefer I make private until further notice, I can do that. Just trying to get this out of the way now.

**Comment by cwulfman** [comment]
> hi @cwulfman and @lcerrato I kind of like the idea of creating a new repository where we could move texts that are finished and passing and free of any rights issues.

I have no strong opinions on this; I guess I was imagining that Lisa was going to (1) rename this repo to something like "Renaissance texts" and keep it private; then (2) create a new repo named canonical-engLit that would be public and would, as @AlisonBabeu suggests, be the home for all the texts being converted to P6.  That way there would be a repository of the files pre-Epidoc that could be archived.

**Comment by cwulfman** [comment]
> If you would prefer I make private until further notice, I can do that. Just trying to get this out of the way now.

I think we should leave it just as you've fixed it up now, @lcerrato -- it's a fine solution.

**Comment by lcerrato** [comment]
@cwulfman @AlisonBabeu 
I think whatever the two of you want is fine. I was under the impression Greg wanted me to test the build, so I did the expeditious thing. When I was asked to make it so, I thought that meant, make this public.
As I said, this isn't my repo by any stretch. 

If you want me to go back and move stuff around, please let me know.

**Comment by lcerrato** [comment]
@gregorycrane 
Is there anything in this collection that should not be public? Is anything restricted in any way?

**Comment by lcerrato** [comment]
Greg affirmed this can be public.
