### ISSUE TITLE
castList and castItem missing in EpiDoc schema

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/canonical-engLit#9]
The TEI drama module was designed to support encoding of dramatic texts printed using common Western conventions. We used <castList> and <castItem> when encoding Shakespeare and Marlowe.

What should be the preferred translation of these elements into EpiDoc?

**Comment by lcerrato** [comment]
Drama is poorly handled. Anything that is not within a line number will not currently display, so front matter is usually a note or a comment. There is a dummy line "0" to force the first speaker label to appear. (It should be a hidden label but the software displays it).

It would be good to come up with something better — the Greek was rushed through for a class, so it is not great.
Unfortunately, this is one area where EpiDoc is not ideal and the Viewer probably needs some refinement for these cases.

There are some notes about speaker vs said, labels, and split lines in the wiki I can dig up, but the most recent work would be Euripides English translations.
